apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cluster
  namespace: argocd
  labels:
    app.kubernetes.io/name: postgres-cluster
    app.kubernetes.io/part-of: infrastructure
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  
  source:
    repoURL: https://github.com/travelspirit-infra/terraform-hcloud-kube-hetzner
    targetRevision: HEAD
    path: deployments/postgres/manifests
    
  destination:
    server: https://kubernetes.default.svc
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    
  # Health check ignores for PostgreSQL operator
  ignoreDifferences:
  - group: postgresql.cnpg.io
    kind: Cluster
    jsonPointers:
    - /status
    - /spec/postgresql/parameters/archive_mode
    - /spec/postgresql/parameters/archive_timeout
    - /spec/postgresql/parameters/dynamic_shared_memory_type
    - /spec/postgresql/parameters/full_page_writes
    - /spec/postgresql/parameters/log_destination
    - /spec/postgresql/parameters/log_directory
    - /spec/postgresql/parameters/log_filename
    - /spec/postgresql/parameters/log_rotation_age
    - /spec/postgresql/parameters/log_rotation_size
    - /spec/postgresql/parameters/log_truncate_on_rotation
    - /spec/postgresql/parameters/logging_collector
    - /spec/postgresql/parameters/max_parallel_workers
    - /spec/postgresql/parameters/max_replication_slots
    - /spec/postgresql/parameters/max_worker_processes
    - /spec/postgresql/parameters/shared_memory_type
    - /spec/postgresql/parameters/shared_preload_libraries
    - /spec/postgresql/parameters/ssl_max_protocol_version
    - /spec/postgresql/parameters/ssl_min_protocol_version
    - /spec/postgresql/parameters/wal_keep_size
    - /spec/postgresql/parameters/wal_level
    - /spec/postgresql/parameters/wal_log_hints
    - /spec/postgresql/parameters/wal_receiver_timeout
    - /spec/postgresql/parameters/wal_sender_timeout
    - /spec/replicationSlots
    - /spec/monitoring
    - /spec/enablePDB
    - /spec/failoverDelay
    - /spec/logLevel
    - /spec/maxSyncReplicas
    - /spec/minSyncReplicas
    - /spec/postgresGID
    - /spec/postgresUID
    - /spec/primaryUpdateMethod
    - /spec/smartShutdownTimeout
    - /spec/startDelay
    - /spec/stopDelay
    - /spec/postgresql/syncReplicaElectionConstraint
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/selector/cnpg.io~1podRole