# Values for VTB API deployment on K8s cluster (using Harbor registry)
# Override values for the K8s test environment

replicaCount: 1

image:
  repository: harbor.travelspirit.cloud/library/api
  pullPolicy: IfNotPresent
  tag: 'latest'

# ARM64 tolerations for Hetzner CAX instances
tolerations:
  - key: architecture
    value: arm64
    effect: NoSchedule

# Environment-specific configuration
environment: test

# Ingress configuration for K8s cluster
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
  hosts:
    - host: tst.api.visualtourbuilder.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wildcard-api-visualtourbuilder-com-tls
      hosts:
        - tst.api.visualtourbuilder.com

# Database configuration (CloudNativePG)
database:
  host: postgres-rw.postgres.svc.cluster.local
  port: 5432
  name: appdb
  user: appuser
  # Password should be set via secret

# Resource limits for K8s
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 256m
    memory: 512Mi

# Health checks (using /health endpoint, not /health/liveness)
healthCheck:
  enabled: true
  path: /health
  port: 3000
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5