formatter: "markdown table"

version: ">= 0.16.0, < 1.0.0"

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: ""
 
output:
  file: docs/terraform.md
  mode: replace

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 3
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true