apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
  labels:
    app: otel-collector
data:
  otel-collector-config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'node-exporter'
              scrape_interval: 30s
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - monitoring
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app]
                  action: keep
                  regex: node-exporter
                - source_labels: [__meta_kubernetes_pod_node_name]
                  action: replace
                  target_label: node
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: pod
                - source_labels: [__meta_kubernetes_pod_container_name]
                  action: replace
                  target_label: container
                - source_labels: [__address__]
                  action: replace
                  regex: ([^:]+)(?::\d+)?
                  replacement: $1:9100
                  target_label: __address__
    
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
        send_batch_max_size: 15000
      
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 128
      
      resource:
        attributes:
        - key: cluster
          value: k3s-cluster
          action: insert
        - key: environment
          value: production
          action: insert
    
    exporters:
      prometheusremotewrite:
        endpoint: "https://prometheus.travelspirit.cloud/api/v1/write"
        tls:
          insecure_skip_verify: true
        resource_to_telemetry_conversion:
          enabled: true
        add_metric_suffixes: true
        headers:
          X-Scope-OrgID: "travelspirit"
        sending_queue:
          enabled: true
          queue_size: 10000
          num_consumers: 5
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
      
      debug:
        verbosity: normal
        sampling_initial: 5
        sampling_thereafter: 200
    
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      
      pprof:
        endpoint: 0.0.0.0:1777
      
      zpages:
        endpoint: 0.0.0.0:55679
    
    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch, resource]
          exporters: [prometheusremotewrite, debug]
      telemetry:
        logs:
          level: info
        metrics:
          level: detailed
          address: 0.0.0.0:8888