{{- if .Values.connectionInfo.enabled }}
---
# ConfigMap with connection information
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-connection-info
  namespace: postgres
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  # Connection strings for applications
  primary_host: "postgres-rw.postgres.svc.cluster.local"
  readonly_host: "postgres-ro.postgres.svc.cluster.local"
  any_host: "postgres-r.postgres.svc.cluster.local"
  port: "5432"
  database: {{ .Values.postgresql.database.name | quote }}
  # Example connection string (without password for security)
  connection_string: "postgresql://{{ .Values.postgresql.database.owner }}:PASSWORD@postgres-rw.postgres.svc.cluster.local:5432/{{ .Values.postgresql.database.name }}?sslmode=require"
{{- end }}