{{- if .Values.services.readWrite.enabled }}
---
# Service for read-write connections (primary)
apiVersion: v1
kind: Service
metadata:
  name: postgres-rw
  namespace: postgres
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: read-write
spec:
  type: {{ .Values.services.readWrite.type }}
  selector:
    cnpg.io/cluster: {{ .Values.postgresql.cluster.name }}
    role: primary
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
{{- end }}

{{- if .Values.services.readOnly.enabled }}
---
# Service for read-only connections (standby)
apiVersion: v1
kind: Service
metadata:
  name: postgres-ro
  namespace: postgres
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: read-only
spec:
  type: {{ .Values.services.readOnly.type }}
  selector:
    cnpg.io/cluster: {{ .Values.postgresql.cluster.name }}
    role: replica
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
{{- end }}

{{- if .Values.services.readAny.enabled }}
---
# Service for read connections (any instance)
apiVersion: v1
kind: Service
metadata:
  name: postgres-r
  namespace: postgres
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: read-any
spec:
  type: {{ .Values.services.readAny.type }}
  selector:
    cnpg.io/cluster: {{ .Values.postgresql.cluster.name }}
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
{{- end }}