kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: hcloud-csi-controller
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: hcloud-csi-controller
    spec:
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:canary
          imagePullPolicy: Always
        - name: csi-resizer
          image: quay.io/k8scsi/csi-resizer:canary
          imagePullPolicy: Always
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:canary
          imagePullPolicy: Always
        - name: hcloud-csi-driver
          image: hetznercloud/hcloud-csi-driver:latest
          imagePullPolicy: Always
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:canary
          imagePullPolicy: Always
      volumes:
        - name: socket-dir
          emptyDir: {}
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: hcloud-csi-node
  namespace: kube-system
  labels:
    app: hcloud-csi
spec:
  selector:
    matchLabels:
      app: hcloud-csi
  template:
    spec:
      containers:
        - name: csi-node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:canary
          imagePullPolicy: Always
        - name: hcloud-csi-driver
          image: hetznercloud/hcloud-csi-driver:latest
          imagePullPolicy: Always
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:canary
          imagePullPolicy: Always