# Install cert-manager for SSL certificate management
# Apply with: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager